{{- $host := .Values.ingressHost -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $host }}
      http:
        paths:
{{- range $path, $serviceName := .Values.paths.frontend }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 3000
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $host }}
      http:
        paths:
{{- range $path, $serviceName := .Values.paths.employee }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 8083
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attendance-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $host }}
      http:
        paths:
{{- range $path, $serviceName := .Values.paths.attendance }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 8081
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: salary-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $host }}
      http:
        paths:
{{- range $path, $serviceName := .Values.paths.salary }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: 8080
{{- end }}

---
# apiVersion: networking.k8s.io/v1
# kind: IngressClass
# metadata:
#   name: traefik
# spec:
#   controller: traefik.io/ingress-controller

